# Generated by Django 3.1.2 on 2020-11-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
