# Generated by Django 3.1.2 on 2020-11-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20201119_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.skillmodel')),
            ],
        ),
        migrations.CreateModel(
            name='filterskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.skillmodel')),
            ],
        ),
    ]
