# Generated by Django 3.1.2 on 2020-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_filterskill_institutedetails_skillmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='photo',
            field=models.ImageField(default='hii', upload_to='images'),
        ),
    ]
