# Generated by Django 3.1.2 on 2020-11-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insadmin', '0002_skillmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedetails',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insadmin.skillmodel'),
        ),
    ]
